version: '3.8'
services:

  transpiler:
    build:
      context: .
      dockerfile: ./transpiler/Dockerfile
    container_name: showveo-transpiler
    restart: unless-stopped
    volumes:
      - ./:/app
    logging:
      options:
        max-file: '3'
        max-size: '1m'

  queue:
    image: rabbitmq:3-management
    container_name: showveo-queue
    hostname: showveo-queue
    ports:
      - 5672:5672
      - 15672:15672
    restart: unless-stopped
    volumes:
      - /queue:/var/lib/rabbitmq

  database:
    image: 'mongo'
    container_name: showveo-database
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./db:/data/db

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: showveo-api
    network_mode: host
    restart: unless-stopped
    volumes:
      - ~/media:/media
      - ./:/app
    depends_on:
      - database
      - transpiler

  indexer:
    build:
      context: .
      dockerfile: ./indexer/Dockerfile
    container_name: showveo-indexer
    restart: unless-stopped
    volumes:
      - ~/media:/media
      - ./:/app
    depends_on:
      - queue
      - database
      - transpiler
    ports:
      - 9001:9001

  converter:
    build:
      context: .
      dockerfile: ./converter/Dockerfile
    container_name: showveo-converter
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    volumes:
      - ~/media:/media
      - ./:/app
    depends_on:
      - queue
      - database
      - transpiler
    ports:
      - 9002:9002

  metadata:
    build:
      context: .
      dockerfile: ./metadata/Dockerfile
    container_name: showveo-metadata
    restart: unless-stopped
    volumes:
      - ./:/app
      - ./static/images:/data/images
    depends_on:
      - queue
      - database
      - transpiler
    ports:
      - 9003:9003

  subtitler:
    build:
      context: .
      dockerfile: ./subtitler/Dockerfile
    container_name: showveo-subtitler
    restart: unless-stopped
    volumes:
      - ~/media:/media
      - ./:/app
    depends_on:
      - queue
      - database
      - transpiler
    ports:
      - 9004:9004
  
  static:
    image: nginx
    container_name: showveo-static
    restart: unless-stopped
    volumes:
      - ./static/nginx.conf:/etc/nginx/nginx.conf
      - ./static/images:/data/images
    ports:
      - 12002:12002