version: '2.3'
services:
  queue:
    image: rabbitmq:3-management
    container_name: video-streamer-queue
    hostname: video-streamer-queue
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped
    volumes:
      - /queue:/var/lib/rabbitmq
  data:
    image: 'mongo'
    container_name: video-streamer-database
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: video-streamer-api
    restart: unless-stopped
    ports:
      - 8101:8101
      - 8009:8009
    volumes:
      - ~/media:/media
      - ./:/app
    depends_on:
      - queue
      - data
  indexer:
    build:
      context: .
      dockerfile: ./indexer/Dockerfile
    container_name: video-streamer-indexer
    restart: unless-stopped
    volumes:
      - ~/media:/media
      - ./:/app
    depends_on:
      - queue
      - data
  converter:
    build:
      context: .
      dockerfile: ./converter/Dockerfile
    container_name: video-streamer-converter
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /usr/local/cuda:/cuda
      - ~/media:/media
      - ./:/app
    depends_on:
      - queue
      - data
  subtitler:
    build:
      context: .
      dockerfile: ./subtitler/Dockerfile
    container_name: video-streamer-subtitler
    restart: unless-stopped
    volumes:
      - ~/media:/media
      - ./:/app
    depends_on:
      - queue
      - data
  metadata:
    build:
      context: .
      dockerfile: ./metadata/Dockerfile
    container_name: video-streamer-metadata
    restart: unless-stopped
    volumes:
      - ./:/app
    depends_on:
      - queue
      - data
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    container_name: video-streamer-web
    restart: unless-stopped
    ports:
      - 80:8080
      - 1606:1606
    volumes:
      - ./:/app
    depends_on:
      - api