version: '3.7'
services:
  queue:
    image: rabbitmq:3-management
    container_name: video-streamer-queue
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped
  data:
    image: 'mongo'
    container_name: video-streamer-database
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./db:/data/db
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: video-streamer-api
    restart: unless-stopped
    ports:
      - 8101:8101
    volumes:
      - ~/media:/media
      - ./:/app
    depends_on:
      - queue
      - data
  indexer:
    build:
      context: .
      dockerfile: ./indexer/Dockerfile
    container_name: video-streamer-indexer
    restart: unless-stopped
    volumes:
      - ~/media:/media
      - ./:/app
    depends_on:
      - queue
      - data