version: '2.3'
services:
  queue:
    image: rabbitmq:3-management
    container_name: showveo-queue
    hostname: showveo-queue
    network_mode: host
    restart: unless-stopped
    volumes:
      - /queue:/var/lib/rabbitmq
  data:
    image: 'mongo'
    container_name: showveo-database
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./db:/data/db
  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: showveo-api
    restart: unless-stopped
    network_mode: host
    volumes:
      - ~/media:/media
      - ./:/app
    depends_on:
      - queue
      - data
    ports:
      - 9000:9000
  indexer:
    build:
      context: .
      dockerfile: ./indexer/Dockerfile
    container_name: showveo-indexer
    restart: unless-stopped
    volumes:
      - ~/media:/media
      - ./:/app
    ports:
      - 9001:9001
    depends_on:
      - queue
      - data
  converter:
    build:
      context: .
      dockerfile: ./converter/Dockerfile
    container_name: showveo-converter
    restart: unless-stopped
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /usr/local/cuda:/cuda
      - ~/media:/media
      - ./:/app
    ports:
      - 9002:9002
    depends_on:
      - queue
      - data
  subtitler:
    build:
      context: .
      dockerfile: ./subtitler/Dockerfile
    container_name: showveo-subtitler
    restart: unless-stopped
    volumes:
      - ~/media:/media
      - ./:/app
    ports:
      - 9003:9003
    depends_on:
      - queue
      - data
  metadata:
    build:
      context: .
      dockerfile: ./metadata/Dockerfile
    container_name: showveo-metadata
    restart: unless-stopped
    volumes:
      - ./:/app
    ports:
      - 9004:9004
    depends_on:
      - queue
      - data